<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Блоги");
?><?$APPLICATION->IncludeComponent(
	"bitrix:blog",
	"blog_bootstrap_v5",
	Array(
		"AJAX_PAGINATION" => "N",
		"ALLOW_POST_CODE" => "Y",
		"ALLOW_POST_MOVE" => "N",
		"BLOG_COUNT" => "20",
		"BLOG_COUNT_MAIN" => "6",
		"BLOG_PROPERTY" => "",
		"BLOG_PROPERTY_LIST" => "",
		"CACHE_TIME" => "3600",
		"CACHE_TIME_LONG" => "604800",
		"CACHE_TYPE" => "A",
		"COLOR_TYPE" => "Y",
		"COMMENTS_COUNT" => "25",
		"COMMENTS_LIST_VIEW" => "Y",
		"COMMENT_ALLOW_IMAGE_UPLOAD" => "A",
		"COMMENT_ALLOW_VIDEO" => "Y",
		"COMMENT_EDITOR_CODE_DEFAULT" => "N",
		"COMMENT_EDITOR_DEFAULT_HEIGHT" => "200",
		"COMMENT_EDITOR_RESIZABLE" => "Y",
		"COMMENT_PROPERTY" => "",
		"COMPONENT_TEMPLATE" => ".default",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"EDITOR_CODE_DEFAULT" => "N",
		"EDITOR_DEFAULT_HEIGHT" => "300",
		"EDITOR_RESIZABLE" => "Y",
		"GROUP_ID" => array(0=>"1",1=>"",),
		"IMAGE_MAX_HEIGHT" => "",
		"IMAGE_MAX_WIDTH" => "",
		"MESSAGE_COUNT" => "25",
		"MESSAGE_COUNT_MAIN" => "6",
		"MESSAGE_LENGTH" => "100",
		"NAME_TEMPLATE" => "",
		"NAV_TEMPLATE" => "",
		"NOT_USE_COMMENT_TITLE" => "N",
		"NO_URL_IN_COMMENTS" => "",
		"NO_URL_IN_COMMENTS_AUTHORITY" => "",
		"PATH_TO_SMILE" => "/bitrix/images/blog/smile/",
		"PERIOD" => "",
		"PERIOD_DAYS" => "30",
		"PERIOD_NEW_TAGS" => "",
		"POST_PROPERTY" => "",
		"POST_PROPERTY_LIST" => "",
		"RATING_TYPE" => "",
		"SEF_MODE" => "N",
		"SEO_USE" => "Y",
		"SEO_USER" => "N",
		"SET_NAV_CHAIN" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_LOGIN" => "Y",
		"SHOW_NAVIGATION" => "N",
		"SHOW_RATING" => "",
		"SHOW_SPAM" => "N",
		"SMILES_COUNT" => "4",
		"THEME" => "red",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USER_PROPERTY" => "",
		"USER_PROPERTY_NAME" => "",
		"USE_ASC_PAGING" => "N",
		"USE_GOOGLE_CODE" => "Y",
		"USE_SHARE" => "N",
		"VARIABLE_ALIASES" => array("blog"=>"blog","post_id"=>"post_id","user_id"=>"user_id","page"=>"page","group_id"=>"group_id",),
		"WIDTH" => "100%"
	)
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>